obj-$(CONFIG_TYPEC)		+= typec.o
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi.o
obj-$(CONFIG_TYPEC_UCSI_ACPI)	+= ucsi_acpi.o
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm.o
obj-$(CONFIG_TYPEC_TCPCI)	+= tcpci.o
obj-$(CONFIG_TYPEC_CROS_EC)	+= cros_tcpc.o
